### ISSUE TITLE
Question about log message

### ISSUE THREAD

**Issue by PerfectZyx** [CloudWise-OpenSource/GAIA-DataSet#5]
First, thank you for sharing this data set.
I have some questions about the message field in log.

For example,
2021-07-01 10:54:22,639 | INFO | 0.0.0.4 | dbservice1 | permission_operate.py -> permission_operation -> 35 | c124e30fb40651dc | the list of all available services are redisservice1: http://0.0.0.1:9386, redisservice2: http://0.0.0.2:9387

What does this trace id "c124e30fb40651dc" mean？Is there any relationship between this log and this trace?
And What does "permission_operate.py -> permission_operation -> 35" mean？

Thanks a lot.

**Comment by Xander-cloudwise** [comment]
Thank you for your interest in the GAIA dataset.
Firstly, “c124e30fb40651dc” represents trace_id, which is the identifier of trace data and could be matched with the trace_id field in trace data to make log data correspond to trace data. In other words, trace_id represents under which request the log is printed.
Secondly, "permission_operate.py -> permission_operation -> 35" is just a simple log template when printing the error log.
Finally, “%(filename)s -> %(funcName)s -> %(lineno)d |” indicates the error is located in which script, which function and which line.

**Comment by PerfectZyx** [comment]
> Thank you for your interest in the GAIA dataset.
> Firstly, “c124e30fb40651dc” represents trace_id, which is the identifier of trace data and could be matched with the trace_id field in trace data to make log data correspond to trace data. In other words, trace_id represents under which request the log is printed.
> Secondly, "permission_operate.py -> permission_operation -> 35" is just a simple log template when printing the error log.
> Finally, “%(filename)s -> %(funcName)s -> %(lineno)d |” indicates the error is located in which script, which function and which line.

Thanks for your reply!

Can I understand that the printing of this log is related to a call in this trace?

And I have another problem. In the ‘run_table_2021-07.csv’ , only the fault 'wait for 11 seconds for follow-up operations to simulate the login failure of the QR code expired' has relevant information about the trace, and the other faults do not. Does this mean that the fault 'login failure of the QR code expired' is caused by this trace?

**Comment by Xander-cloudwise** [comment]
As for the first question, the answer is yes. 
For the second question, 
the “run_table_xx” table records the behavior that we actively inject anomaly information, which means each record in the “run_table_xx” table is the root cause of anomalies of log and trace data. The reason that the fault mentioned here has trace_id is that this action will only lead to a single trace or log to produce anomalies. However, in the same time, other identical requests are normal. Therefore, adding the trace_id is helpful for the subsequent verification of algorithm results.

**Comment by PerfectZyx** [comment]
> As for the first question, the answer is yes.
> For the second question,
> the “run_table_xx” table records the behavior that we actively inject anomaly information, which means each record in the “run_table_xx” table is the root cause of anomalies of log and trace data. The reason that the fault mentioned here has trace_id is that this action will only lead to a single trace or log to produce anomalies. However, in the same time, other identical requests are normal. Therefore, adding the trace_id is helpful for the subsequent verification of algorithm results.

Okay, I get it.. Thanks again for your reply.
