### ISSUE TITLE
Question about MicroSS Data

### ISSUE THREAD

**Issue by PerfectZyx** [CloudWise-OpenSource/GAIA-DataSet#6]
In "metric" folder, each csv filename contains the node to which the file belongs. In "business" folder, each file contains the business log of a node. But in "trace" folder, "service_name" is the name of service or host. 
What is the difference between a service and a node here?
And why some nodes have the corresponding metric but no associated logs and traces?
I would also like to know the relationship between nodes and containers here, for example, is each node here deployed in a container?

Thanks a lot.

**Comment by PerfectZyx** [comment]
Sorry, I also want to ask in the "metric" folder, “system...” is about the host metrics？

**Comment by Xander-cloudwise** [comment]
Thank you for your interest in the GAIA dataset.
  Firstly, a service and a node are in the same meaning.
  Secondly, some services are not application nodes (such as zookeeper), so there is no logs and traces; some nodes are abstract application nodes without directly collected trace and log data.
  Thirdly, the service nodes here, except for the abstract nodes, are all deployed in containers.
  Finally, in the metric folder, "system..." is the metrics of server.

**Comment by PerfectZyx** [comment]
> Thank you for your interest in the GAIA dataset.
> Firstly, a service and a node are in the same meaning.
> Secondly, some services are not application nodes (such as zookeeper), so there is no logs and traces; some nodes are abstract application nodes without directly collected trace and log data.
> Thirdly, the service nodes here, except for the abstract nodes, are all deployed in containers.
> Finally, in the metric folder, "system..." is the metrics of server.

Sorry, maybe I didn't describe it clearly, I would like to ask if all microservices on a host are deployed in the same container or each microservice is deployed in a container?

**Comment by Xander-cloudwise** [comment]
Thanks again for your valuable questions. In response to your second question, each microservice is deployed in a container.

**Comment by PerfectZyx** [comment]
Thank you for your patient answers, which gave me a deeper understanding of this data!
